name: "Poll"

on:
  push:
  pull_request:

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Repack everything"
        run: |
          make repack

      - name: "Check for uncommitted changes"
        run: |
          git diff --exit-code